### ISSUE TITLE
ZeRO-DP experiments

### ISSUE THREAD

**Issue by hyunwoongko** [EleutherAI/magiCARP#16]
Since DeepSpeed has a lot of features, I've split the issue. I will test the ZeRO-DP first.

**Comment by hyunwoongko** [comment]
@LouisCastricato before we merge new PR, we should check multi-gpu compatibility.
<img width="774" alt="스크린샷 2022-03-10 오후 5 14 24" src="https://user-images.githubusercontent.com/38183241/157617536-d59c60d1-4b94-46bf-b32a-ac2878844f79.png">

**Comment by LouisCastricato** [comment]
Which pr is this

**Comment by hyunwoongko** [comment]
the main branch

**Comment by shahbuland** [comment]
Navigate to the code where this is happening and replace self.model.config.grad_clip with self.config.grad_clip  
If config  is coming back as a dict, then it's getting  the HF models config, not our ModelConfig object.
This *should* fix but needs to be tested, and I can't test at the moment.
