### ISSUE TITLE
Deepspeed and multiGPU support

### ISSUE THREAD

**Issue by LouisCastricato** [EleutherAI/magiCARP#4]
We need to be able to split the contrastive parallel batch between GPUs for the multiGPU setting rather than using DeepSpeed's naive data parallelism.

In particular, using vanilla CARP as reference, 

The passage encoder contrastive parallel

https://github.com/EleutherAI/magiCARP/blob/f4f880f7ede3420226d3e41267c1c41d48264a2e/carp/pytorch/model/architectures/carp.py#L61

and the review encoder contrastive parallel

https://github.com/EleutherAI/magiCARP/blob/f4f880f7ede3420226d3e41267c1c41d48264a2e/carp/pytorch/model/architectures/carp.py#L73

can be split between GPUs by sending a subset of the microbatches to its own GPU.

Similarly, the review and passage encoder do not need to be computed in serial- as long as we gather in parallel.

**Comment by LouisCastricato** [comment]
cc @dashstander

**Comment by dashstander** [comment]
So the idea here being to use torch.distributed to do the microbatches and/or doing the review/passage encoding separately? Because the deepspeed API isn't fine-grained enough to do that kind of custom data parallel?

**Comment by hyunwoongko** [comment]
@LouisCastricato @shahbuland Oh there was already an issue. 
so I did not create a new one and assigned myself here. :)
